### PR TITLE
Add partial failures on sqs batch items

### PR DESCRIPTION
**Pull request by johsjo**

### CODE REVIEW

**Review by jens-peterolsson — COMMENTED** [review]
LGTM. The only thing I'm thinking about is if it's really necessary to have a specific extractor for this, couldn't it just be part of the general sqs extractor? Afaik if the consumer hasn't set the property `ReportBatchItemFailures`, anything reported as `BatchItemFailures`will just be ignored anyway.

If we do it like this we should probably upgrade version from 3 to 4 though just to be safe. Regardless, version should go to minimum 3.1.0 and not 3.0.1 imo.

**Comment by johsjo** [comment]
@jens-peterolsson Thank you for your feedback. The problem we have solved with a specific extractor is to get access to the MessageId via SQSMessageEnvelope. Im not really sure how we can update the old extractor to make this work. :thinking:

**Comment by jens-peterolsson** [comment]
> @jens-peterolsson Thank you for your feedback. The problem we have solved with a specific extractor is to get access to the MessageId via SQSMessageEnvelope. Im not really sure how we can update the old extractor to make this work. 🤔

@johsjo I see. My reasoning is that it doesn't really make sense to choose from a client perspective if you want the extractor with support for partial failures or not. If you have configured it in your template, you definitely do want it and it's just extra work configuring it in code as well. Whereas if you haven't configured it in template, it will still work only without partial retry. So I would argue if we can make a breaking change (as mentioned with updated major version) that is fairly simple to upgrade to, I think it might be worth it. If it is not easy to upgrade, then I support the idea of leaving the existing interface unchanged.

**Comment by jaknor** [comment]
@jens-peterolsson not quite sure if we are talking about the same thing. When you say extractor, are you referring to the `SQSMessageExtractor` class? The client doesn't choose extractor class, only the base class it inherits from. If you are referring to the `SQSMessagePartialFailureProcessorBase` class then I don't think regular SQS can use it as it catches all errors and returns them as partial failures which won't work if not set on the template.

I agree that the `SQSMessageExtractorForPartialFailure` will work in either case for SQS, but this extractor doesn't share an interface with the extractors for SNS and Kinesis so it is not possible to use in MessageProcessorBase

**Comment by jaknor** [comment]
I've had another go which can be seen here https://github.com/mhlabs/MhLabs.PubSubExtensions/pull/19 

This time I've decoupled the handling of the different event types from each other. This leads to slightly more duplication of code for event handlers, but means we can have different signatures for the Process methods which I believe makes it easier to understand what is going on and allows SQS to return data without forcing SNS/Kinesis to do it as well. 

I've built the SQS handler so that it can handle both with and without partial failure. I see the following pros/cons

- Pros
  - No `NotImplementedException`
  - Clearer separation between different event types
  - Easier for consumers to know which one to choose, only one option for each event type
- Cons
  - Even if you do not care about partial batch failure you have to return a response
  - Additional configuration required for partial batch failure to make sure error handling works

The upgrade path would be to replace MessageProcessorBase with the correct class for your event type and for SQS to update your `HandleEvent` method to match the new signature.

**Comment by jaknor** [comment]
Closing this in favor of #19

**Pull request closed without merging**
